WITH CAH AS (
    SELECT 
        h.HISTORY_ID, 
        h.CAR_ID, 
        c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) AS BaseFEE, 
        CASE
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 90 THEN '90일 이상'
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 30 THEN '30일 이상'
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 7 THEN '7일 이상'
            ELSE '할인 없음'
        END AS DurationType
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

SELECT 
    CAH.HISTORY_ID,
    ROUND(BaseFEE * (1 - COALESCE(CDP.DISCOUNT_RATE, 0) * 0.01), 0) AS FEE
FROM CAH CAH
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CDP 
ON CAH.DurationType = CDP.DURATION_TYPE AND CDP.CAR_TYPE = '트럭'
ORDER BY FEE DESC, CAH.HISTORY_ID DESC;