WITH CAR_AND_HISTORY AS (
    SELECT 
        h.HISTORY_ID, 
        h.CAR_ID, 
        c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1) AS BaseFEE, 
        h.START_DATE, 
        h.END_DATE,
        CASE
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 90 THEN 
                (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 30 THEN 
                (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) >= 7 THEN 
                (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')
            ELSE 0
        END AS DiscountRate
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = '트럭'
)

SELECT 
    HISTORY_ID,
    ROUND(BaseFEE * (1 - DiscountRate * 0.01), 0) AS FEE
FROM CAR_AND_HISTORY
ORDER BY FEE DESC, HISTORY_ID DESC;
